### ISSUE TITLE
Версия!

### ISSUE THREAD

**Issue by mvictorl** [xsltdev/angdev.ru#4]
Отличный сайт по Angular!
Но не плохо бы указать в самом начале для какой версии Angular данный материал.
А также отметить места, которые изменились в новой версии.
Ну, а еще лучше - актуализировать всё...

Спасибо!

**Comment by bndby** [comment]
В данный ммомент не работаю с ангуляром, а свободное время занято другими проектами. Только ПРы рассматриваю, сори.
